services:

    db:
      extends:
        file: docker-compose-base.yml
        service: db
      ports:
        - "127.0.0.1:27017:27017/tcp"
      volumes:
        - ${DATA_DIR:-$HOME/afb/var}/db:/data/db:cached

    server:
      build:
        context: .
        dockerfile: ${SRC_DIR:-$HOME/src}/atomic-fishbowl-server/Dockerfile-dev
        args:
          NODE_VERSION: ${NODE_VERSION:-16.15.0}
      environment:
        LOG_LEVEL: ${LOG_LEVEL:-debug}
        MONGO_HOST: db
        MONGO_PORT: 27017
        MONGO_AUTH: "false"
        SSL_CERT_HOSTNAME: ${SSL_CERT_HOSTNAME:-afb-dev.kensington.local}
        SSL_CERT_ALT_HOSTNAME: ${SSL_CERT_ALT_HOSTNAME:-afb-dev}
      restart: unless-stopped
      deploy:
        restart_policy:
          condition: on-failure
      stdin_open: true
      tty: true
      volumes:
        - ${SRC_DIR:-$HOME/src}:/home/node/src:cached
        - ${CONF_DIR:-$HOME/afb/etc}/certificates:/etc/kentech/afb/certificates:rw,z
        - ${DATA_DIR:-$HOME/afb/var}/collections:/var/kentech/afb/collections:rw,z,cached
        - ${DATA_DIR:-$HOME/afb/var}/server:/var/kentech/afb/server:rw,z,cached

    client:
      build:
        context: .
        dockerfile: ${SRC_DIR:-$HOME/src}/atomic-fishbowl-client/Dockerfile-dev
      restart: unless-stopped
      deploy:
        restart_policy:
          condition: on-failure
      stdin_open: true
      tty: true
      volumes:
        - ${SRC_DIR:-$HOME/src}:/home/node/src:cached

    nginx:
      build:
        context: .
        dockerfile: ${SRC_DIR:-$HOME/src}/atomic-fishbowl-client/Dockerfile-nginx-dev
        args:
          NGINX_VERSION: ${NGINX_VERSION:-1.22.0}
      ports:
        - "${NGINX_PORT:-444}:443/tcp"
      depends_on:
        - server
      # command: ["wait-for-it", "-t", "0", "server:3002", "--", "nginx-debug", "-g", "daemon off;"]
      command: ["wait-for-it", "-t", "0", "server:3002", "--", "nginx", "-g", "daemon off;"]
      volumes:
        - ${SRC_DIR:-$HOME/src}/atomic-fishbowl-client/nginx.conf.dev:/etc/nginx/nginx.conf:ro
        - ${CONF_DIR:-$HOME/afb/etc}/certificates:/etc/nginx/certificates:ro,z
        - ${DATA_DIR:-$HOME/afb/var}/collections:/var/kentech/afb/collections:z,cached
